# Generated by Django 5.1.7 on 2025-08-23 02:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=users.models.business_file_upload_to),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.business_file_upload_to),
        ),
    ]
