# Generated by Django 5.1.7 on 2025-09-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_business_documents_alter_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmaterial',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
