# Generated by Django 5.1.7 on 2025-07-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('agent', 'Agent'), ('client', 'Client')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration_in_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_limit', models.IntegerField(blank=True, null=True)),
                ('priority_support', models.BooleanField(default=False)),
                ('instant_alerts', models.BooleanField(default=False)),
                ('relationship_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='subscription.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_status', models.CharField(blank=True, max_length=40, null=True)),
                ('subscription_start_date', models.DateField(auto_now_add=True)),
                ('subscription_end_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('subscription_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplanvariant')),
            ],
        ),
    ]
