# Generated by Django 5.1.7 on 2025-06-13 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('purchased_from', models.CharField(blank=True, max_length=150, null=True)),
                ('purchased_type', models.CharField(blank=True, max_length=150, null=True)),
                ('property_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=150)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('receipt', 'Receipt')], max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='transaction_documents/')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='property.property')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('purchased', 'Purchased')], max_length=20)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_properties', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_properties', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
