# Generated by Django 5.1.7 on 2025-07-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperty',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('sold', 'Sold')], max_length=20),
        ),
    ]
