# Generated by Django 5.1.7 on 2025-07-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_no', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('property_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_username', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_id', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_company_commissions', to='users.user')),
                ('buyer_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_id', to='users.user')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_commissions', to='property.property')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_commissions', to='transactions.transaction')),
                ('percentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_commissions', to='commissions.commissionmaster')),
            ],
        ),
    ]
